#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII
#flameshot &
mpd &
mpc &
blueman-applet &
#dropbox &

#/usr/bin/emacs --daemon &

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Zathura state=tiled
#bspc rule -a evince desktop="^3" follow=on
bspc rule -a Emacs state=tiled
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a mpv state=fullscreen
# Border
#bspc config focused_border_color        "#6c71c4"
#bspc config normal_border_color         "#073642"
#bspc config active_border_color         "#073642"

#Dracula Scheme
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

# For Dracula you can add cyan color.
#bspc config normal_border_color "#44475a"
#bspc config active_border_color "#6272a4"
#bspc config focused_border_color "#8be9fd"
#bspc config presel_feedback_color "#6272a4"

# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
#/usr/bin/lxpolkit &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
bash $HOME/.config/bspwm/.fehbg
#nitrogen --restore &
#dwall -s room &
#feh --randomize --bg-fill ~/wallpapers/*
#wallee &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/
# Picom
picom &
# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

