#!/bin/bash

# Prompt user for the anime name
anime_name=$(echo "" | dmenu -p "Enter the name of the anime:")

# Define the available options
options=("Normal Opening" "Quality Options" "History Options" "Download")

# Combine the anime name with the options
prompted_options=("$anime_name" "${options[@]}")

# Prompt user to choose an option using dmenu with a limit of 10 items
chosen_option=$(printf '%s\n' "${prompted_options[@]}" | dmenu -l 10 -p "Choose action for '$anime_name':")

# Depending on the chosen option, execute the corresponding action
case $chosen_option in
    "$anime_name")
        echo "Anime: $anime_name"
        ;;
    "Normal Opening")
        ani-cli "$anime_name"
        ;;
    "Quality Options")
        # Define quality options
        quality_options=("480p" "720p" "1080p" "1440p" "2160p")
        # Prompt user to choose quality using dmenu
        chosen_quality=$(printf '%s\n' "${quality_options[@]}" | dmenu -p "Choose quality option for '$anime_name':")
        ani-cli -q "$chosen_quality" "$anime_name"
        ;;
    "History Options")
        ani-cli -H "$anime_name"
        ;;
    "Download")
        ani-cli -d "$anime_name"
        ;;
    *)
        echo "Invalid option"
        ;;
esac

