#!/usr/bin/env bash

set -euo pipefail

# WORD="$(rofi -dmenu -i -p "Search:")"
WORD="$(echo 'Search any Word' | dmenu -i -p 'Search:')"
TESTWORD="$(dym -c -n=1 "$WORD")"

if [ "$WORD" != "$TESTWORD" ]; then
	KEYWORD=$(dym -c "$WORD" | dmenu -i -l 10 -p "was $WORD a misspelling?(select/no)")
	if [ "$KEYWORD" = "no" ] || [ "$KEYWORD" = "n" ]; then
		KEYWORD="$WORD"
	fi
else
	KEYWORD="$WORD"
fi

if ! [ "${KEYWORD}" ]; then
	printf 'No word inserted\n' >&2
	exit 0
fi
st -e trans -v -d "$WORD"
