#!/usr/bin/env bash

# script name: dm-music

# Author: Murtaza Udaipurwala

# Description:
# - Music player using dmenu
# - A simpler alternative to music players like ncmpcpp, moc, cmus
# - Uses mpd in the backend

# Features
# - Select and play music from mpd music directory
# - Queue a playlist

# Dependencies:
# 1. rofi
# 2. mpd(music player daemon)
# 3. mpc(terminal command to access mpd)

# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.
set -euo pipefail

help(){
    printf "Run dm-music without any arguments for all available music\n
    dm-music [options]
    -h\tdisplays this help page
    -q\tQueue a playlist
    -p\tSelect music for the queued playlist\n
    ### Some useful mpc command
    mpc toggle\t\t\ttoggle between pause and play state
    mpc next\t\t\tgo to next track
    mpc prev\t\t\tgo to prev track
    mpc seekthrough +00:00:10\tseek 10s forward
    mpc seekthrough -00:00:10\tseek 10s backward\n"
}

play(){
    mpc crop > /dev/null 2>&1
    music="$(mpc listall | dmenu -i -l 5 -p "Music to play")" || exit 1
    mpc -q add "$music"
    mpc del 0 > /dev/null 2>&1
    mpc play
    mpc repeat on
}

queuePlaylist(){
    playlist="$(mpc lsplaylists | dmenu -i -l 5 -p "Your playlists")" || exit 1
    mpc -q clear
    mpc load "$playlist"
    mpc -q play 1
    echo "$playlist" > "${HOME}/.cache/current_playlist"
}

currentPlaylist(){
    playlist="$(mpc lsplaylists | dmenu -i -l 5 -p "Select a playlist to play")" || exit 1
    music_list="$(mpc playlist "${playlist}")"
    music="$(echo "${music_list}" | dmenu -i -l 5 -p "Music to play")" || exit 1
    mpc -q clear
    mpc load "${playlist}" > /dev/null 2>&1
    mpc play "$(echo "${music_list}" | awk -v pattern="$music" '$0 ~ pattern { print NR; exit }')"
}

while true; do
    choice=$(printf "Play\nQueue Playlist\nCurrent Playlist\nHelp" | dmenu -i -p "Choose an option") || exit
    case "$choice" in
        "Play") play ;;
        "Queue Playlist") queuePlaylist ;;
        "Current Playlist") currentPlaylist ;;
        "Help") man /dev/stdin <<EOF
$(help)
EOF
exit 0 ;;
          *) echo "Invalid option";;
    esac
done

