#!/usr/bin/env bash

declare -A options
options=(["Edit Config Files"]=~/.dwm/scripts/confedit ["Record The Screen"]=~/.dwm/scripts/sc_record ["Convert Currencies"]=~/.dwm/scripts/currencies ["Open Dictionary"]=~/.dwm/scripts/dict ["Check the IP Address"]=~/.local/bin/dmip ["Kill an Existing Process"]=~/.dwm/scripts/kill ["Open Man Page of an Installed Program"]=~/.dwm/scripts/man ["Pick a color"]=~/.local/bin/dm-colpick ["See Latest Reddit Posts"]=~/.dwm/scripts/reddit ["Set New Background"]=~/.dwm/scripts/changelook ["Cross check the spelling"]=~/.dwm/scripts/spellcheck ["Translate to Different Language"]=~/.local/bin/dm-translate ["Search Through web(WebSearch)"]=~/.dwm/scripts/websearch ["Look through Arch Wiki Docs"]=~/.dwm/scripts/archwiki ["Listen to Radio"]=~/.dwm/scripts/radio ["Listen to Music"]=~/.dwm/scripts/music ["Connect to WIFI"]=~/.dwm/scripts/wifi_rofi ["Connect to BLUETOOTH"]=~/.dwm/scripts/bluetooth ["Open PowerMenu"]=~/.dwm/scripts/power)

choice=$(printf '%s\n' "${!options[@]}" | sort -g | dmenu -i -l 15 -p 'Choose an Option: ' "${@}")

if [ "$choice" ]; then
    sh "${options[$choice]}"

# What to do if we just escape without choosing anything.
else
  echo "Program terminated." && exit 0
fi
