#!/bin/bash

# Check if WhatsApp is already running
if pgrep -f "FFPWA-01HRCGK100QJKXF0034NJXQCYC" > /dev/null
then
    dunstify "WhatsApp is already running"
else
    # Start WhatsApp
    firefoxpwa site launch 01HRCGK100QJKXF0034NJXQCYC
    dunstify "WhatsApp started"
fi

