#!/usr/bin/env bash
#
# script name: dm-wifi
# Description: Connect to wifi using dmenu
# Dependencies: dmenu, nmcli, Any Nerd Font

DMENU="dmenu -i -l 100 -p"

main() {
  # Use awk to extract BSSID and network names without cutting the line
  # bssid=$(nmcli device wifi list | sed -n '1!p' | awk '{print $1}' | ${DMENU} "Select Wifi  :" )
  bssid=$(nmcli device wifi list | sed -n '1!p' | cut -b 9- | ${DMENU} "Select Wifi  :" | cut -d' ' -f1)
  pass=$(echo "" | ${DMENU} "Enter Password  :")
  # We are disabling a shellcheck warning about using && and || as it doesn't apply here.
  # shellcheck disable=SC2015
  [ -n "$pass" ] && nmcli device wifi connect "$bssid" password "$pass" || nmcli device wifi connect "$bssid"
  sleep 10
  if ping -q -c 2 -W 2 google.com >/dev/null; then
    dunstify "Your internet is working :)"
  else
    dunstify "Your internet is not working :("
  fi
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"

