#!/bin/bash

wall=$(find /mnt/Extras/dotfiles/home/user/Pictures/Wall -type f -name "*.jpg"  -o -name "*.png" | shuf -n 1)

xwallpaper --zoom $wall

wal -c
wal -i $wall
xdotool key super+F5
rm -rf ~/.walcache/
mkdir ~/.walcache
cp $wall ~/.walcache/1
dunstify "Colours changed according to Wallpaper..."
betterlockscreen -u ~/.walcache/1
