#!/bin/bash

wall=$(find /home/ram/dotfiles/home/user/Pictures/Wall -type f -name "*.jpg" -o -name "*.png" | shuf -n 1)

xwallpaper --zoom $wall

wal -c
wal -i $wall
xdotool key super+F5
rm -rf ~/.walcache/
mkdir ~/.walcache
cp $wall ~/.walcache/1
betterlockscreen -u ~/.walcache/1
