#+title: Mu4e Setup

* This is a setup  of MU4E mail on Emacs
** Dependencies
*** Emacs
*** mu, mbsync (paru -S mu mbsync-git)
** After instaling dependencies we have to create a folder named mu4e in ~/.config directory
*** In that create a file named .mbsyncrc in home directory
*** Paste the following in that


IMAPAccount gmail
Host imap.gmail.com
User chagantivenkataramireddy1@gmail.com
PassCmd "gpg2 -q --for-your-eyes-only --no-tty -d ~/.config/mu4e/mbsyncpass-acc1.gpg"
SSLType IMAPS
CertificateFile /etc/ssl/certs/ca-certificates.crt

IMAPStore gmail-remote
Account gmail

MaildirStore gmail-local
Subfolders Verbatim
Path ~/Mail/Gmail
Inbox ~/Mail/Gmail/Inbox

Channel gmail
Master :gmail-remote:
Slave :gmail-local:
Patterns * ![Gmail]* "[Gmail]/Sent Mail" "[Gmail]/Starred" "[Gmail]/All Mail" "[Gmail]/Trash"
Create Both
SyncState *

*** Now you can add another account if you need but just change the chaga1 directory to another name ... and also change the email.
*** Also change the gpg file name also .
*** Now create a file named mbsyncpass-acc1 in the same directory or whatever name you can use and enter only password of your gmail in that file and save it.
*** After that create the directory what you name like Mail/chaga1(use your own name) ..
*** Now we have to encrypt that file so open termial in that directory and type
    (gpg2 -c mbsyncpass-acc1)
**** After encrypting the file remove the original file for security puposes.
*** Now type
     (time mu init --maildir=~/Mail/ --my-address='email@address')

*** After that we have to download our mails so type
    (time mbsync -c ~/.mbsyncrc -a)

** You have two-factor authentication turned on:
*** Now go to (https://myaccount.google.com/apppasswords?rapt=AEjHL4OSkRaaGvcObqcIfRLvyHFbu2m5-h4GkvKcTtKCAPFH-mCYtR9rpRp5uzttDVHjFLOsN02h8MVyWCiy-2jzH8eOWGikEQ) and add a device and website you can add anything according to your requirement then copy the 12 or 16 digit password and paste that into mbsync-acc1 file instead of your password that's it you mails will be downloaded ... Then type the same command as above.
** Now just open Emacs and type M-x and select mu4e option and type y for every thing and just copy my snippet of code for mu4e and that's it mu4e setup is completed

**** If you have two address then do

mu init --maildir=~/Mail \
          --my-address=chagantivenkataramireddy1@gmail.com \
          --my-address=chagantivenkataramireddy4@gmail.com

** You can add an authinfo file in your home directory and add thsi to file

#+begin_quote
machine smtp.gmail.com login "gmail-name" password "password" port "port number"
#+end_quote
